/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project_template.app;

import project_template.list.LinkedList;

import static project_template.utilities.StringUtils.join;
import static project_template.utilities.StringUtils.split;
import static project_template.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
